name: Tangle

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  tangle:
    runs-on: ubuntu-latest
    steps:
      - uses: gwennlbh/to-tangled@v0.3
        with:
          repo: aylac.top/atproto-basic-notifications
          ssh-key: ${{ secrets.TANGLED_KEY }}
